language: python

dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2

services:
  - redis-server

install:
  - pip install -q django~=$DJANGO.0
  - pip install coveralls
  - pip install mockredispy
  - pip install django-redis-cache
  - pip install 'celery<5'
  - python setup.py develop

script:
  - PYTHONPATH=$PYTHONPATH:$PWD coverage run --source=defender $(which django-admin.py) test defender --settings=defender.travis_settings
  - coverage report -m

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0
    - python: "2.7"
      env: DJANGO=2.1
    - python: "2.7"
      env: DJANGO=2.2
    - python: "3.4"
      env: DJANGO=2.0
    - python: "3.4"
      env: DJANGO=2.1
    - python: "3.4"
      env: DJANGO=2.2

after_success:
  - coveralls --verbose
